apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - -echotext="This is the blog site!"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echoserver
  name: echoserver
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: echoserver
  type: ClusterIP